import { courseSections, diseases, glossaryTerms, sourceManuals } from '../data';
import { CourseSection, DiseaseEntry, GlossaryTerm, ManualId } from '../types';

export type AssistantSource = { kind: 'section' | 'term' | 'disease'; id: string; title: string; excerpt: string; manualId?: ManualId; sectionId?: string; score: number };
export type AssistantContext = { query: string; sources: AssistantSource[]; sections: CourseSection[]; terms: GlossaryTerm[]; diseases: DiseaseEntry[] };
const words = (q: string) => q.toLowerCase().split(/[^a-zа-яё0-9]+/i).filter(w => w.length > 2);
const scoreText = (query: string, text: string) => { const ws = words(query); const hay = text.toLowerCase(); return ws.reduce((s,w) => s + (hay.includes(w) ? 2 : 0) + (hay.split(w).length - 1) * 0.3, 0); };
export function rankSectionsByQuery(query: string, sections = courseSections) { return sections.map(item => ({ item, score: scoreText(query, `${item.title} ${item.content} ${item.keyTerms.join(' ')} ${item.tags.join(' ')}`) })).filter(x => x.score > 0).sort((a,b) => b.score - a.score); }
export function rankTermsByQuery(query: string, terms = glossaryTerms) { return terms.map(item => ({ item, score: scoreText(query, `${item.term} ${item.definition} ${item.expandedExplanation} ${item.tags.join(' ')}`) })).filter(x => x.score > 0).sort((a,b) => b.score - a.score); }
export function rankDiseasesByQuery(query: string, rows = diseases) { return rows.map(item => ({ item, score: scoreText(query, `${item.name} ${item.alternativeNames?.join(' ')} ${item.genes} ${item.inheritanceType} ${item.symptoms.join(' ')} ${item.pathogenesis}`) })).filter(x => x.score > 0).sort((a,b) => b.score - a.score); }
export function searchKnowledgeBase(query: string): AssistantSource[] { const sections = rankSectionsByQuery(query).slice(0,5).map(({item,score}) => ({ kind:'section' as const, id:item.id, title:item.title, excerpt:item.content.slice(0,420), manualId:item.manualId, sectionId:item.id, score })); const terms = rankTermsByQuery(query).slice(0,5).map(({item,score}) => ({ kind:'term' as const, id:item.id, title:item.term, excerpt:item.definition, manualId:item.manualId, sectionId:item.sectionId, score })); const dis = rankDiseasesByQuery(query).slice(0,5).map(({item,score}) => ({ kind:'disease' as const, id:item.id, title:item.name, excerpt:`${item.inheritanceType}. Симптомы: ${item.symptoms.join(', ')}. ${item.pathogenesis || ''}`, manualId:item.manualId, sectionId:item.sectionId, score })); return [...sections, ...terms, ...dis].sort((a,b)=>b.score-a.score).slice(0,10); }
export function buildAssistantContext(query: string): AssistantContext { const sources = searchKnowledgeBase(query); return { query, sources, sections: sources.filter(s=>s.kind==='section').map(s=>courseSections.find(x=>x.id===s.id)!).filter(Boolean), terms: sources.filter(s=>s.kind==='term').map(s=>glossaryTerms.find(x=>x.id===s.id)!).filter(Boolean), diseases: sources.filter(s=>s.kind==='disease').map(s=>diseases.find(x=>x.id===s.id)!).filter(Boolean) }; }
export function formatSourcesForAnswer(sources: AssistantSource[]) { return sources.map((s,i) => `${i+1}. ${s.title}${s.manualId ? ` (${sourceManuals.find(m=>m.id===s.manualId)?.title || s.manualId})` : ''}`).join('\n'); }
