import { SimulatorResult } from '../types';

export type Dominance = 'dominant' | 'recessive' | 'codominant' | 'incomplete' | 'lethal';
export type DominanceModel = 'complete' | 'incomplete' | 'codominant' | 'multipleAlleles' | 'lethal' | 'epistasis' | 'complementary' | 'polymeric' | 'linked' | 'abo' | 'rh' | 'x-linked' | 'y-linked' | 'mitochondrial';
export interface Allele { symbol: string; label: string; dominance: Dominance; effect?: string }
export interface GeneModel { id: string; name: string; alleles: Allele[]; chromosome: 'autosome' | 'X' | 'Y' | 'mtDNA'; dominanceModel: DominanceModel; phenotypeRules?: Record<string,string> }
export interface CrossInput { modelType?: string; parent1Genotype: string; parent2Genotype: string; genes?: GeneModel[]; recombinationFrequency?: number; phenotypeRuleSet?: string; showLargeSquare?: boolean; inheritanceType?: string; model?: string }

type ParsedGenotype = { raw: string; loci: string[][]; linked?: string[]; warnings: string[] };
export const simulatorPresets = [
 { name:'Aa × Aa', p1:'Aa', p2:'Aa', model:'complete' }, { name:'Aa × aa', p1:'Aa', p2:'aa', model:'complete' }, { name:'AaBb × AaBb', p1:'AaBb', p2:'AaBb', model:'complete' }, { name:'IAi × IBi', p1:'IAi', p2:'IBi', model:'abo' }, { name:'IAIB × ii', p1:'IAIB', p2:'ii', model:'abo' }, { name:'Dd × dd для Rh', p1:'Dd', p2:'dd', model:'rh' }, { name:'XAXa × XAY', p1:'XAXa', p2:'XAY', model:'x-linked' }, { name:'XAXa × XaY', p1:'XAXa', p2:'XaY', model:'x-linked' }, { name:'XaXa × XAY', p1:'XaXa', p2:'XAY', model:'x-linked' }, { name:'Митохондриальное: больная мать', p1:'mt*', p2:'mt', model:'mitochondrial' }, { name:'Митохондриальное: больной отец', p1:'mt', p2:'mt*', model:'mitochondrial' }, { name:'Комплементарность 9:7', p1:'AaBb', p2:'AaBb', model:'complementary' }, { name:'Доминантный эпистаз 13:3', p1:'AaBb', p2:'AaBb', model:'epistasis-13-3' }, { name:'Рецессивный эпистаз 9:3:4', p1:'AaBb', p2:'AaBb', model:'epistasis-9-3-4' }, { name:'Полимерия 1:4:6:4:1', p1:'A1a1A2a2', p2:'A1a1A2a2', model:'polygenic' }, { name:'Сцепление AB/ab × ab/ab, r=20%', p1:'AB/ab', p2:'ab/ab', model:'linked', recombinationFrequency:20 }
];
const tokenize = (genotype:string) => genotype.match(/I[AB]|X[Aa]?|Y|mt\*?|[A-ZА-ЯЁ]\d?|[a-zа-яё]\d?/g)||[];
const keyOf = (t:string) => t.startsWith('I')||t==='i'?'ABO':t.startsWith('X')||t==='Y'?'sex':t.replace(/[a-zа-яё]/g,m=>m.toUpperCase());
export function parseGenotypeAdvanced(input:string): ParsedGenotype { const raw=input.trim(); const warnings:string[]=[]; if(!raw) return {raw,loci:[],warnings:['Введите генотип, например Aa или AaBb']}; if(raw.includes('/')) return {raw,loci:[],linked:raw.replace(/\/\//g,'/').split('/').filter(Boolean),warnings}; if(raw.includes('mt')) return {raw,loci:[[raw]],warnings}; const tokens=tokenize(raw); if(!tokens.length) warnings.push('Не удалось распознать аллели'); const groups:Record<string,string[]>={}; tokens.forEach(t=>{ const k=keyOf(t); groups[k]=[...(groups[k]||[]),t]; }); const loci=Object.values(groups).map(g=>g.length===1?[g[0],g[0]]:g.slice(0,2)); return {raw,loci,warnings}; }
export function generateGametesAdvanced(genotype:string, options:{ model?:string; recombinationFrequency?:number }={}){ const parsed=parseGenotypeAdvanced(genotype); if(parsed.linked){ const [h1='',h2='']=parsed.linked; const r=Math.max(0,Math.min(options.recombinationFrequency ?? 0,50)); if(r<=0) return Array.from(new Set([h1,h2])); if(r>=50) return generateGametesAdvanced(h1+h2,{model:'complete'}); const rec1=`${h1[0]||''}${h2[1]||''}`, rec2=`${h2[0]||''}${h1[1]||''}`; return Array.from(new Set([h1,h2,rec1,rec2].filter(Boolean))); } let out=['']; parsed.loci.forEach(pair=>{ out=out.flatMap(prefix=>Array.from(new Set(pair)).map(a=>prefix+a)); }); return Array.from(new Set(out)); }
export const generateGametes = (genotype:string) => generateGametesAdvanced(genotype);
export function normalizeGenotype(genotype:string){ const toks=tokenize(genotype); if(genotype.includes('/')) return genotype; return toks.sort((a,b)=>keyOf(a).localeCompare(keyOf(b)) || b.localeCompare(a)).join('') || genotype; }
export function calculateRatios(items:string[]){ return items.reduce<Record<string,number>>((acc,item)=>{acc[item]=(acc[item]||0)+1; return acc;},{}); }
const hasDom=(g:string,l:string)=>g.includes(l.toUpperCase()); const homoRec=(g:string,l:string)=>!hasDom(g,l);
export function phenotypeFromGenotype(genotype:string, model='complete'){ if(model==='mitochondrial') return genotype.startsWith('mt*')||genotype.includes('mt*mt')?'дети матери с mtDNA-вариантом':'обычный митохондриальный вариант'; if(model==='abo'){ const hasA=genotype.includes('IA'), hasB=genotype.includes('IB'); return hasA&&hasB?'группа AB':hasA?'группа A':hasB?'группа B':'группа O'; } if(model==='rh') return genotype.includes('D')?'Rh+':'Rh-'; if(model==='x-linked') return genotype.includes('XaY')?'больной мужчина':genotype.includes('XaXa')?'больная женщина':genotype.includes('XAXa')||genotype.includes('XaXA')?'носительница':'здоровый фенотип'; if(model==='y-linked') return genotype.includes('Y')?'мужчина с Y-сцепленным признаком':'нет Y-сцепленного признака'; if(model==='complementary'||model==='epistasis-9-7') return hasDom(genotype,'A')&&hasDom(genotype,'B')?'признак проявлен (A_B_)':'нет признака (9:7)'; if(model==='epistasis-13-3') return hasDom(genotype,'A')||homoRec(genotype,'b')?'эпистатический фенотип (13)':'рецессивный фенотип bb при aa (3)'; if(model==='epistasis-9-3-4') return homoRec(genotype,'a')?'рецессивный эпистаз aa (4)':hasDom(genotype,'B')?'A_B_ фенотип (9)':'A_bb фенотип (3)'; if(model==='polygenic'){ const n=(genotype.match(/[A-ZА-ЯЁ]\d?/g)||[]).length; return `${n} доз(ы) доминантных аллелей`; } if(model==='linked') return genotype.includes('A')&&genotype.includes('B')?'оба доминантных признака':'рекомбинантный/рецессивный фенотип'; return /[A-ZА-ЯЁ]/.test(genotype)?'доминантный фенотип':'рецессивный фенотип'; }
export function buildPunnettSquareAdvanced(gametes1:string[], gametes2:string[], model='complete'){ return gametes1.map(g1=>gametes2.map(g2=>{ const genotype=normalizeGenotype(g1+g2); return {g1,g2,genotype,phenotype:phenotypeFromGenotype(genotype,model)}; })); }
export function explainCross(result:SimulatorResult,input:CrossInput){ const total=Object.values(result.genotypeRatios).reduce((a,b)=>a+b,0)||1; const phen=Object.entries(result.phenotypeRatios).map(([k,v])=>`${k}: ${v}/${total} (${Math.round(v/total*100)}%)`).join('; '); return `Скрещивание ${input.parent1Genotype} × ${input.parent2Genotype}. Сгенерированы гаметы: ${result.gametes1.join(', ')} и ${result.gametes2.join(', ')}. Модель: ${input.modelType||input.model||'complete'}. Фенотипическое распределение: ${phen}.` }
export function simulateCross(inputOrP1:CrossInput|string, p2?:string, model='complete'): SimulatorResult { const input:CrossInput=typeof inputOrP1==='string'?{parent1Genotype:inputOrP1,parent2Genotype:p2||'',modelType:model}:{...inputOrP1,modelType:inputOrP1.modelType||inputOrP1.model||inputOrP1.inheritanceType||'complete'}; const m=input.modelType||'complete'; const warnings=[...parseGenotypeAdvanced(input.parent1Genotype).warnings,...parseGenotypeAdvanced(input.parent2Genotype).warnings]; const gametes1=m==='mitochondrial'?[input.parent1Genotype]:generateGametesAdvanced(input.parent1Genotype,{model:m,recombinationFrequency:input.recombinationFrequency}); const gametes2=m==='mitochondrial'?['mt']:generateGametesAdvanced(input.parent2Genotype,{model:m,recombinationFrequency:input.recombinationFrequency}); const tooLarge=gametes1.length*gametes2.length>64&&!input.showLargeSquare; const all=buildPunnettSquareAdvanced(gametes1,gametes2,m); const flat=all.flat(); const genotypeRatios=calculateRatios(flat.map(c=>c.genotype)); const phenotypeRatios=calculateRatios(flat.map(c=>c.phenotype||'')); if(tooLarge) warnings.push('Решётка больше 8×8: таблица скрыта, показаны соотношения.'); const result:SimulatorResult={id:crypto.randomUUID?.(),input:{inheritanceType:m,parent1Genotype:input.parent1Genotype,parent2Genotype:input.parent2Genotype,model:m,recombination:input.recombinationFrequency},gametes1,gametes2,punnettSquare:tooLarge?[]:all,square:tooLarge?[]:all,genotypeRatios,phenotypeRatios,warning:warnings[0],warnings,explanation:'',sourceTheory:'Учебная модель: результаты являются вероятностной схемой для тренировки.'}; result.explanation=explainCross(result,input); return result; }
export const simulateABO=(p1:string,p2:string)=>simulateCross({parent1Genotype:p1,parent2Genotype:p2,modelType:'abo'});
export const simulateRh=(p1:string,p2:string)=>simulateCross({parent1Genotype:p1,parent2Genotype:p2,modelType:'rh'});
export const simulateXLinked=(input:CrossInput)=>simulateCross({...input,modelType:'x-linked'});
export const simulateYLinked=(input:CrossInput)=>simulateCross({...input,modelType:'y-linked'});
export const simulateMitochondrial=(input:CrossInput)=>simulateCross({...input,modelType:'mitochondrial'});
export const simulateComplementary=(input:CrossInput)=>simulateCross({...input,modelType:'complementary'});
export const simulateEpistasis=(input:CrossInput)=>simulateCross({...input,modelType:input.phenotypeRuleSet||'epistasis-9-3-4'});
export const simulatePolygenic=(input:CrossInput)=>simulateCross({...input,modelType:'polygenic'});
export const simulateLinkedGenes=(input:CrossInput)=>simulateCross({...input,modelType:'linked'});
export const simulateInheritance = (input:{parent1Genotype:string; parent2Genotype:string; model?:string; inheritanceType?:string; recombination?:number}) => simulateCross({parent1Genotype:input.parent1Genotype,parent2Genotype:input.parent2Genotype,modelType:input.model || input.inheritanceType || 'complete',recombinationFrequency:input.recombination});
