import { SimulatorResult } from '../types';
export const simulatorPresets = [
 { name:'Aa × Aa', p1:'Aa', p2:'Aa', model:'complete' }, { name:'Aa × aa', p1:'Aa', p2:'aa', model:'complete' }, { name:'AaBb × AaBb', p1:'AaBb', p2:'AaBb', model:'complete' }, { name:'IAi × IBi', p1:'IAi', p2:'IBi', model:'abo' }, { name:'Dd × dd для Rh', p1:'Dd', p2:'dd', model:'complete' }, { name:'XAXa × XAY', p1:'XAXa', p2:'XAY', model:'x-linked' }, { name:'XAXa × XaY', p1:'XAXa', p2:'XaY', model:'x-linked' }, { name:'Митохондриальное: больная мать', p1:'mt*', p2:'mt', model:'mitochondrial' }, { name:'Комплементарность 9:7', p1:'AaBb', p2:'AaBb', model:'complementary' }, { name:'Доминантный эпистаз 13:3', p1:'AaBb', p2:'AaBb', model:'epistasis' }, { name:'Полимерия 1:4:6:4:1', p1:'A1a1A2a2', p2:'A1a1A2a2', model:'polygenic' }
];
function loci(genotype:string){ if(genotype.includes('mt')) return [[genotype]]; const tokens=genotype.match(/I[AB]|X[Aa]?|Y|[A-ZА-ЯЁ]\d?|[a-zа-яё]\d?/g)||[]; const groups:Record<string,string[]>={}; tokens.forEach(t=>{ const key=t.startsWith('I')?'ABO':t.startsWith('X')||t==='Y'?'sex':(t.match(/[A-Za-zА-Яа-яЁё]+\d?/g)?.[0]||t).replace(/[a-zа-яё]/g,m=>m.toUpperCase()); groups[key]=[...(groups[key]||[]),t]; }); return Object.values(groups).map(g=>g.length===1?[g[0],g[0]]:g.slice(0,2)); }
export function generateGametes(genotype:string){ const ls=loci(genotype); let out=['']; ls.forEach(pair=>{ out=out.flatMap(prefix=>Array.from(new Set(pair)).map(a=>prefix+a)); }); return Array.from(new Set(out)); }
function normalizeGenotype(g:string){ const toks=g.match(/I[AB]|X[Aa]?|Y|[A-ZА-ЯЁ]\d?|[a-zа-яё]\d?/g)||[g]; return toks.sort((a,b)=>a.toLowerCase().localeCompare(b.toLowerCase()) || a.localeCompare(b)).join(''); }
function phenotype(genotype:string, model='complete'){ if(model==='mitochondrial') return genotype.includes('mt*')?'все дети унаследуют митохондриальный вариант от матери':'обычный митохондриальный вариант'; if(model==='abo'){ const hasA=genotype.includes('IA'), hasB=genotype.includes('IB'); return hasA&&hasB?'группа AB':hasA?'группа A':hasB?'группа B':'группа O'; } if(model==='x-linked') return genotype.includes('XaY')?'больной мужчина':genotype.includes('XaXa')?'больная женщина':genotype.includes('XAXa')?'носительница':'здоровый фенотип'; if(model==='complementary') return /A/.test(genotype)&&/B/.test(genotype)?'оба доминантных гена — признак проявлен':'нет комплементарности'; if(model==='epistasis') return /A/.test(genotype)||!/B/.test(genotype)?'эпистатический фенотип':'рецессивный фенотип b'; if(model==='polygenic'){ const n=(genotype.match(/[A-ZА-ЯЁ]\d?/g)||[]).length; return `${n} доз(ы) доминантных аллелей`; } return /[A-ZА-ЯЁ]/.test(genotype)?'доминантный фенотип':'рецессивный фенотип'; }
export function simulateCross(parent1Genotype:string, parent2Genotype:string, model='complete'): SimulatorResult { const gametes1=generateGametes(parent1Genotype), gametes2=generateGametes(parent2Genotype); const tooLarge=gametes1.length*gametes2.length>64; const genotypeRatios:Record<string,number>={}, phenotypeRatios:Record<string,number>={}; const punnettSquare = tooLarge ? [] : gametes1.map(g1=>gametes2.map(g2=>{ const genotype=normalizeGenotype(g1+g2); genotypeRatios[genotype]=(genotypeRatios[genotype]||0)+1; const ph=phenotype(genotype,model); phenotypeRatios[ph]=(phenotypeRatios[ph]||0)+1; return {g1,g2,genotype}; })); if(tooLarge){ gametes1.forEach(g1=>gametes2.forEach(g2=>{ const genotype=normalizeGenotype(g1+g2); genotypeRatios[genotype]=(genotypeRatios[genotype]||0)+1; const ph=phenotype(genotype,model); phenotypeRatios[ph]=(phenotypeRatios[ph]||0)+1; })); }
 return { gametes1, gametes2, punnettSquare, genotypeRatios, phenotypeRatios, warning: tooLarge?'Решётка слишком большая: показаны только соотношения.':undefined, explanation:`Сгенерированы гаметы (${gametes1.join(', ')}) и (${gametes2.join(', ')}). Модель: ${model}. Генотипические и фенотипические доли рассчитаны по всем сочетаниям гамет.` };
}
export const simulateInheritance = (input:{parent1Genotype:string; parent2Genotype:string; model?:string; inheritanceType?:string}) => simulateCross(input.parent1Genotype, input.parent2Genotype, input.model || input.inheritanceType || 'complete');
